# 기본 설정 (공통)
spring:
  profiles:
    active: prod  # 기본값은 dev 프로필

# 공통 설정들
jwt:
  secret: ${JWT_SECRET:default-jwt-secret}

management:
  endpoints:
    web:
      base-path: /actuator
  endpoint:
    info:
      enabled: true