# 기본 설정 (공통)
spring:
  profiles:
    active: dev  # 기본값은 dev 프로필

# 공통 설정들
jwt:
  secret: ${JWT_SECRET:default-jwt-secret}

management:
  endpoints:
    web:
      base-path: /actuator
  endpoint:
    info:
      enabled: true
pinpal:
  jwt:
    access-token:
      secret: ${ACCESS_TOKEN_SECRET}
      expiration-ms: ${ACCESS_TOKEN_EXPIRATION_MS}
    refresh-token:
      secret: ${REFRESH_TOKEN_SECRET}
      expiration-ms: ${REFRESH_TOKEN_EXPIRATION_MS}